language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
  - sudo apt-get update
  - sudo apt-get install cmake
  - mkdir build
  - cd build
  - cmake ..
  - sudo pip install cpp-coveralls wheel

script:
  - make
  - python setup.py install
