language: cpp

compiler:
  - gcc
  - clang

before_script:
  - bash setup-travis.sh
  - mkdir build
  - cd build
  - cmake ..
  - sudo pip install cpp-coveralls wheel

script:
  - make
  - python setup.py install
